server:
  port: 8903
spring:
  application:
    name: ant-web-admin
  zipkin:
    base-url: http://127.0.0.1:9411/
    discovery-client-enabled: false
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
